### ISSUE TITLE
Single fastq file issue

### ISSUE THREAD

**Issue by devmaan** [jyesselm/dreem#3]
Hi, I'm having an issue when trying to input a single fastq file.

When I run the code
`dreem -fa ATP9.fasta -fq1 SRR3929621/SRR3929621_pass.fastq`

I get the following output
```
[18:21 bit_vector.py run] INFO ran at commandline as:
[18:21 bit_vector.py run] INFO /home/devin/anaconda3/bin/dreem -fa ATP9.fasta -fq1 SRR3929621/SRR3929621_pass.fastq
[18:21 bit_vector.py validate_files] INFO fasta file: ATP9.fasta exists
[18:21 bit_vector.py validate_files] INFO fastq file: SRR3929621/SRR3929621_pass.fastq exists
Traceback (most recent call last):
  File "/home/devin/anaconda3/bin/dreem", line 8, in <module>
    sys.exit(main())
  File "/home/devin/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/devin/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/devin/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/devin/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/devin/anaconda3/lib/python3.9/site-packages/dreem/run.py", line 89, in main
    run(args)
  File "/home/devin/anaconda3/lib/python3.9/site-packages/dreem/run.py", line 97, in run
    setup_parameters(args)
  File "/home/devin/anaconda3/lib/python3.9/site-packages/dreem/parameters.py", line 267, in setup_parameters
    parameters = pf.get_parameters(args)
  File "/home/devin/anaconda3/lib/python3.9/site-packages/dreem/parameters.py", line 143, in get_parameters
    inputs = ParametersFactory._Inputs(input_files)
  File "/home/devin/anaconda3/lib/python3.9/site-packages/dreem/parameters.py", line 23, in __init__
    self.fastq2 = paths[2]  # fastq2 input file
IndexError: list index out of range
```
It doesn't happen when I input paired end fastq sequencing files. Is there anything I can do to get it running with a single fastq file?

Thanks.

**Comment by jyesselm** [comment]
Did you pull from main? I think this is an old issue?
